---
- name: Install Docker
  hosts: all
  any_errors_fatal: true
  vars:
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: latest
    ocker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: docker
        state: latest
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
